function L2_str = fmri_getL2def

L2_str = struct(...
    'expt_name', [],...
    'images', [],...
    'evtnames', [],...
    'blknames', [],...
    'subjectid', [],...
    'voldim', [],...
    'qbrainmask', [],...
    'mergedblkbeta',[],...
    'mergedevtbeta', [],...
    'mergedevtbetash', [],...
    'aROI', struct,...
    'fROI', struct,...
    'depstr', struct,...
    'fields', []...
    );

n = 0;
n = n + 1; L2_str.fields{n,1} = 'expt_name              -> name of the experiment';
n = n + 1; L2_str.fields{n,1} = 'images                 -> {nimgs x 1} images used in the event design';
n = n + 1; L2_str.fields{n,1} = 'evtnames               -> {nsubj x 1}{nimgs x 1} image names used in the event design';
n = n + 1; L2_str.fields{n,1} = 'blknames       `       -> {nsubj x 1}{nblks x 1} image category names used in the block design';
n = n + 1; L2_str.fields{n,1} = 'subjectid              -> {nsubj x 1} subject ids';
n = n + 1; L2_str.fields{n,1} = 'voldim                 -> (nsubj x 3) 3D (x,y,nslices) functional volume dimensions';
n = n + 1; L2_str.fields{n,1} = 'qbrainmask             -> {nsubj x 1} (nvoxels x 1) ids of brain mask voxels from evtglm';
n = n + 1; L2_str.fields{n,1} = 'mergedblkbeta          -> {nsubj x 1} (nvoxels x stim) mergedblkbetas';
n = n + 1; L2_str.fields{n,1} = 'mergedevtbeta          -> {nsubj x 1} (nvoxels x stim) mergedevtbetas';
n = n + 1; L2_str.fields{n,1} = 'mergedevtbetash        -> {nsubj x 1} {nvoxels x 1) mergedevtbeta split-halves (from odd & even runs)';

n = n + 1; L2_str.fields{n,1} = 'aROI                   -> structure containing all ROIs from the anatomy toolbox';
n = n + 1; L2_str.fields{n,1} = 'aROI.roiname           -> {nsubj x 1} (nvoxels x 1) ids of the anataomical mask transformed into subject space';

n = n + 1; L2_str.fields{n,1} = 'fROI                   -> structure containing functional contrast masks picked up from dnlocmerged folder';
n = n + 1; L2_str.fields{n,1} = 'fROI.roiname.specs     -> (nsubj x 3) : [isFWE pthresh clusterextent] for each subject from the excelsheet';
n = n + 1; L2_str.fields{n,1} = 'fROI.roiname.contrastnames  -> {nsubj x 1} Contrast names';
n = n + 1; L2_str.fields{n,1} = 'fROI.roiname.ids       -> {nsubj x 1} (nvoxels x 1)';
n = n + 1; L2_str.fields{n,1} = 'fROI.roiname.tvalues   -> {nsubj x 1} (nvoxels x 1)';
n = n + 1; L2_str.fields{n,1} = 'fROI.roiname.runbetas  -> {nsubj x 1} (nfroivoxels x nstim x nreps)';
n = n + 1; L2_str.fields{n,1} = 'fROI.fROIfile          -> name of master XLS file';

n = n + 1; L2_str.fields{n,1} = 'depstr                 -> structure containing all the mfiles used for pipeline and L2 generation';
end